spring.application.name=campusconnect-backend
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.hwexgzaqozrysewjafsv
spring.datasource.password=Sup@b@se2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prachinikam2005@gmail.com
spring.mail.password=knhm vyfz xykp ujxs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=dafjrlqph
cloudinary.api-key=277839339532791
cloudinary.api-secret=EptsH8HbyiFywNQxqpzcVFxP3As

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB